name:                weather
version:             0.1.0.0
github:              "githubuser/weather"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/weather#readme>

dependencies:
- base >= 4.7 && < 5
- direct-sqlite
- resourcet
- conduit
- http-conduit
- http-types
- conduit-extra
- text
- time
- bytestring

library:
  source-dirs: src
  exposed-modules:     Weather
  build-depends:       base >= 4.7 && < 5
                      ,HDBC
                      ,HDBC-sqlite3
                      ,HaXml
                      ,HTTP >= 4000.2.12
                      ,network-uri
                      ,unordered-containers >= 0.2.5
                      ,aeson >= 0.8.0
                      ,bytestring >= 0.10.4
                      ,resourcet
                      ,text >= 1.1.0
                      ,unordered-containers >= 0.2.5
                      ,aeson >= 0.8.0
                      ,http-client
                      ,servant
                      ,servant-client == 0.11


executables:
  weather-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - weather

tests:
  weather-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - weather
